In [1]:
import os
import pandas as pd

In [4]:
df = pd.read_csv(os.path.join('wikidata','wikidata_raw.csv'))

## Statistiky

In [7]:
sloupce = df.columns.to_list()

In [41]:
statistiky = []
for s in sloupce:
    statka = {}
    statka['sloupec'] = s
    statka['vyplneno'] = len(df[~df[s].isnull()])
    statka['nevyplneno'] = len(df[df[s].isnull()])
    statka['ruznych_hodnot'] = df[s].nunique()
    statistiky.append(statka)
statistiky = pd.DataFrame(statistiky)
statistiky.sort_values(by='nevyplneno')

               sloupec  vyplneno  nevyplneno  ruznych_hodnot
0     interpret_hlavni      1151           0            1151
1                   id      1151           0            1131
2              stazeno      1151           0               1
6             velikost      1148           3              22
3           nazev_wiki      1147           4            1127
4             popis_en      1120          31             702
16         zeme_puvodu      1089          62              67
15        misto_puvodu       999         152             574
10    zacatek_pusobeni       919         232              72
7                zanry       903         248             561
5             popis_cs       823         328             427
24          spotify_id       765         386             754
14              gender       742         409               4
8       datum_narozeni       731         420             695
17           obcanstvi       700         451              88
20            nastroje       590         561             158
21             oceneni       362         789             298
12            zalozeni       309         842              96
19                hlas       178         973              26
22         nabozenstvi        55        1096              30
9          datum_umrti        48        1103              46
11      konec_pusobeni        46        1105              23
23           orientace        44        1107              12
18            etnicita        37        1114              27
13               zanik        14        1137              12
25  spotify_odberatele         9        1142               9

## Čištění

In [21]:
ceskove = df[(df['zeme_puvodu'].isnull()) & (df['popis_cs'].str.contains('česk'))]['interpret_hlavni'].to_list()

In [ ]:
slovaci = ['Kontrafakt',]

In [31]:
puvod_nejisty = ['Welshly Arms',
 'Bodyrockers',
 'Junge Junge',
 'Karin Ann',
 'Flipsyde',
 'The Faim',
 'D.H.T.',
 'Banners',
 'Bodybangers',
 'Justin Jesso',
 'Jc Stewart',
 'Desmod',
 'Novaspace',
 'Djane Housekat',
 'Vinylshakerz',
 'Pascal Letoublon',
 'Rat City',
 'Yall',
 'Younotus',
 'Spankers',
 'Sam And The Womp',
 'Thxsomch',
 'Hi-Tack',
 'Gold 1',
 'Beatfreakz',
 'Dony',
 'Dimitri Vegas',
 'Fragma',
 'Klangkarussell',
 'Aloha From Hell',
 'Karmah',
 'Aquagen',
 'Cian Ducrot',
 'Renforshort',
 'Dave Ramone',
 'Cover Drive',
 'Beach Weather',
 'Urban Cone',
 'Avantasia',
 'Ari Abdul',
 'Bpm',
 'Surfaces',
 'Boston Bun',
 'Switch Disco',
 'Hosh',
 'Jodie Harsh',
 'Public',
 'Ocean Park Standoff',
 'Nicky Your',
 'Nitty',
 'Fiedlerski',
 'Shouse',
 'Clou',
 'Momo',
 'Gladiator',
 'James Harries',
 'Fellas',
 'Five O´Clock Tea',
 'Rebels',
 'Hematom',
 'Highland',
 'Atmo Music']

In [28]:
for x in df[(df['zeme_puvodu'].isnull())]['interpret_hlavni'].to_list():
    if x not in puvod_nejisty:
        ceskove.append(x)

In [29]:
df.loc[df['interpret_hlavni'].isin(ceskove),"zeme_puvodu"]="Česko"

In [51]:
df.loc[df['zeme_puvodu'] == 'Římská říše',"zeme_puvodu"]="Spojené království"

In [30]:
df[(df['zeme_puvodu'].isnull())]['interpret_hlavni'].to_list()

['Welshly Arms',
 'Bodyrockers',
 'Junge Junge',
 'Karin Ann',
 'Flipsyde',
 'The Faim',
 'D.H.T.',
 'Banners',
 'Bodybangers',
 'Justin Jesso',
 'Jc Stewart',
 'Desmod',
 'Novaspace',
 'Djane Housekat',
 'Vinylshakerz',
 'Pascal Letoublon',
 'Rat City',
 'Yall',
 'Younotus',
 'Spankers',
 'Sam And The Womp',
 'Thxsomch',
 'Hi-Tack',
 'Gold 1',
 'Beatfreakz',
 'Dony',
 'Dimitri Vegas',
 'Fragma',
 'Klangkarussell',
 'Aloha From Hell',
 'Karmah',
 'Aquagen',
 'Cian Ducrot',
 'Renforshort',
 'Dave Ramone',
 'Cover Drive',
 'Beach Weather',
 'Urban Cone',
 'Avantasia',
 'Ari Abdul',
 'Bpm',
 'Surfaces',
 'Boston Bun',
 'Switch Disco',
 'Hosh',
 'Jodie Harsh',
 'Public',
 'Ocean Park Standoff',
 'Nicky Your',
 'Nitty',
 'Fiedlerski',
 'Shouse',
 'Clou',
 'Momo',
 'Gladiator',
 'James Harries',
 'Fellas',
 'Five O´Clock Tea',
 'Rebels',
 'Hematom',
 'Highland',
 'Atmo Music']

In [33]:
df.loc[df['interpret_hlavni'] == 'Momo',"datum_narozeni"]=None

In [40]:
df[['interpret_hlavni','konec_pusobeni']].sort_values(by='konec_pusobeni',ascending=True).head(20)

      interpret_hlavni         konec_pusobeni
360            Beatles  +1970-04-10T00:00:00Z
69         John Lennon  +1980-00-00T00:00:00Z
657               Abba  +1982-00-00T00:00:00Z
165            Nirvana  +1994-00-00T00:00:00Z
191          Take That  +1996-00-00T00:00:00Z
987   Notorious B.I.G.  +1997-00-00T00:00:00Z
871   Melanie Thornton  +2001-00-00T00:00:00Z
890         Kollerband  +2005-00-00T00:00:00Z
315            Outkast  +2007-00-00T00:00:00Z
371    Michael Jackson  +2009-00-00T00:00:00Z
431     Lady Sovereign  +2010-00-00T00:00:00Z
339      Amy Winehouse  +2011-00-00T00:00:00Z
241          Sugababes  +2011-00-00T00:00:00Z
598              Aysel  +2012-00-00T00:00:00Z
283              Lmfao  +2012-00-00T00:00:00Z
398           Westlife  +2012-06-23T00:00:00Z
780           B.B.King  +2014-00-00T00:00:00Z
898         Joe Cocker  +2014-00-00T00:00:00Z
1031              Clou  +2014-00-00T00:00:00Z
506      Leonard Cohen  +2016-00-00T00:00:00Z

In [43]:
df[df['gender'] == 'genderfluid']

,interpret_hlavni,id,stazeno,nazev_wiki,popis_en,popis_cs,velikost,zanry,datum_narozeni,datum_umrti,...,zeme_puvodu,obcanstvi,etnicita,hlas,nastroje,oceneni,nabozenstvi,orientace,spotify_id,spotify_odberatele
35,Miley Cyrus,Q4235,True,Miley Cyrus,"American singer, actress, and television perso...","americká herečka, zpěvačka a textařka",člověk,"['pop music', 'country', 'pop rock', 'dance-po...",+1992-11-23T00:00:00Z,NaN,...,Spojené státy americké,['Spojené státy americké'],NaN,"['mezzosoprán', 'alt']","['elektrická kytara', 'akustická kytara', 'kla...",['Time 100'],NaN,['pansexualita'],5YGY8feqx7naU7z4HrwZM6,NaN
104,Demi Lovato,Q41173,True,Demi Lovato,American singer and actress,americká herečka a zpěvačka,člověk,"['pop rock', 'pop music', 'contemporary R&B', ...",+1992-08-20T00:00:00Z,NaN,...,Spojené státy americké,['Spojené státy americké'],NaN,['soprán'],"['hlas', 'kytara', 'klavír', 'bicí souprava']","['GLAAD Vanguard Award', 'Time 100']",NaN,"['pansexualita', 'fluidní sexualita']",6S2OmqARrzebs0tKUEyXyp,NaN

In [53]:
df[df['zeme_puvodu'] == 'Spojené království']

,interpret_hlavni,id,stazeno,nazev_wiki,popis_en,popis_cs,velikost,zanry,datum_narozeni,datum_umrti,...,zeme_puvodu,obcanstvi,etnicita,hlas,nastroje,oceneni,nabozenstvi,orientace,spotify_id,spotify_odberatele
3,Coldplay,Q45188,True,Coldplay,British rock band,britská kapela,hudební skupina,"['alternativní rock', 'pop rock', 'pop music',...",NaN,NaN,...,Spojené království,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4gzpq5DPGxSnKTe4SA8HAU,NaN
32,Calvin Harris,Q81637,True,Calvin Harris,"British DJ, singer and record producer",Skotský DJ a zpěvák,člověk,"['elektropop', 'electro house', 'synthpop', 'd...",+1984-01-17T00:00:00Z,NaN,...,Spojené království,['Skotsko'],NaN,NaN,"['syntezátor', 'hlas', 'basová kytara', 'klaví...",NaN,NaN,NaN,7CajNmpbOovFoOoasH2HaY,NaN
36,Ed Sheeran,Q47447,True,Ed Sheeran,English singer-songwriter,anglický zpěvák a textař,člověk,"['lidová hudba', 'folk pop', 'pop music', 'fol...",+1991-02-17T00:00:00Z,NaN,...,Spojené království,['Spojené království'],NaN,['tenor'],"['kytara', 'hlas', 'live looper']",['Cena Grammy za nejlepší popový sólový výkon'...,NaN,NaN,6eUKZXaKkcviH0Ku9w2n3V,NaN
42,Ellie Goulding,Q31164,True,Ellie Goulding,English singer and songwriter,anglická popová zpěvačka,člověk,"['synthpop', 'elektropop', 'indie pop', 'folkt...",+1986-12-30T00:00:00Z,NaN,...,Spojené království,['Spojené království'],NaN,['soprán'],"['hlas', 'kytara', 'klavír', 'klarinet', 'mand...",NaN,NaN,NaN,0X2BH1fck6amBIoJhDVmmJ,NaN
44,Wham!,Q744087,True,Wham!,English pop duo,anglická hudební skupina,hudební duo,"['pop music', 'nová vlna', 'bílý soul']",NaN,NaN,...,Spojené království,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5lpH0xAS4fVfLkACg9DAuM,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,Dommi,Q110157843,True,We Are Domi,Czech-Norwegian electropop band,česko-norské elektropopové trio,hudební skupina,"['elektropop', 'Scandinavian pop']",NaN,NaN,...,Spojené království,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68nZwIknhC5s9gLHPly09S,NaN
1101,Dido,Q202550,True,Dido,English singer and songwriter (born 1971),britská zpěvačka,člověk,"['pop music', 'pop rock', 'folk']",+1971-12-25T00:00:00Z,NaN,...,Spojené království,['Spojené království'],NaN,"['alt', 'mezzosoprán']","['kytara', 'klavír', 'tamburína', 'hlas', 'bic...",NaN,NaN,NaN,2mpeljBig2IXLXRAFO9AAs,NaN
1115,Bastille,Q689,True,Bastille,English indie pop band,NaN,hudební skupina,['synthpop'],NaN,NaN,...,Spojené království,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7EQ0qTo7fWT7DPxmxtSYEc,NaN
1118,Mumford,Q953918,True,Mumford & Sons,British folk rock band,NaN,hudební skupina,"['rock', 'folk rock', 'folk', 'country']",NaN,NaN,...,Spojené království,NaN,NaN,NaN,NaN,"['Cena Grammy za album roku', 'Juno Award za m...",NaN,NaN,3gd8FJtBJtkRxdfbTu19U2,NaN
1119,Placebo,Q484839,True,Placebo,English alternative rock band,britská hudební skupina,hudební skupina,"['alternativní rock', 'indie rock', 'synth roc...",NaN,NaN,...,Spojené království,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6RZUqkomCmb8zCRqc9eznB,NaN

In [54]:
df.groupby('zeme_puvodu')['interpret_hlavni'].nunique().nlargest(10)

zeme_puvodu
Česko                     289
Spojené státy americké    285
Spojené království        182
Německo                    38
Slovensko                  36
Kanada                     32
Švédsko                    30
Austrálie                  21
Francie                    19
Nizozemsko                 17
Name: interpret_hlavni, dtype: int64